/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as PedirOrcamentoRouteImport } from './routes/pedir-orcamento'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfissionalSlugRouteImport } from './routes/profissional.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as CadastroProfissionalRouteImport } from './routes/cadastro.profissional'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedPainelPerfilRouteImport } from './routes/_authenticated/painel.perfil'
import { Route as AuthenticatedPainelPedidosRouteImport } from './routes/_authenticated/painel.pedidos'
import { Route as AuthenticatedPainelNotificacoesRouteImport } from './routes/_authenticated/painel.notificacoes'
import { Route as AuthenticatedPainelMidiaRouteImport } from './routes/_authenticated/painel.midia'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirOrcamentoRoute = PedirOrcamentoRouteImport.update({
  id: '/pedir-orcamento',
  path: '/pedir-orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalSlugRoute = ProfissionalSlugRouteImport.update({
  id: '/profissional/$slug',
  path: '/profissional/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroProfissionalRoute = CadastroProfissionalRouteImport.update({
  id: '/cadastro/profissional',
  path: '/cadastro/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelPerfilRoute =
  AuthenticatedPainelPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPedidosRoute =
  AuthenticatedPainelPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelNotificacoesRoute =
  AuthenticatedPainelNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelMidiaRoute =
  AuthenticatedPainelMidiaRouteImport.update({
    id: '/midia',
    path: '/midia',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/categorias': typeof CategoriasRoute
  '/entrar': typeof EntrarRoute
  '/pedir-orcamento': typeof PedirOrcamentoRoute
  '/profissionais': typeof ProfissionaisRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/cadastro/profissional': typeof CadastroProfissionalRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/profissional/$slug': typeof ProfissionalSlugRoute
  '/painel/midia': typeof AuthenticatedPainelMidiaRoute
  '/painel/notificacoes': typeof AuthenticatedPainelNotificacoesRoute
  '/painel/pedidos': typeof AuthenticatedPainelPedidosRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/categorias': typeof CategoriasRoute
  '/entrar': typeof EntrarRoute
  '/pedir-orcamento': typeof PedirOrcamentoRoute
  '/profissionais': typeof ProfissionaisRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/cadastro/profissional': typeof CadastroProfissionalRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/profissional/$slug': typeof ProfissionalSlugRoute
  '/painel/midia': typeof AuthenticatedPainelMidiaRoute
  '/painel/notificacoes': typeof AuthenticatedPainelNotificacoesRoute
  '/painel/pedidos': typeof AuthenticatedPainelPedidosRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/categorias': typeof CategoriasRoute
  '/entrar': typeof EntrarRoute
  '/pedir-orcamento': typeof PedirOrcamentoRoute
  '/profissionais': typeof ProfissionaisRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/cadastro/profissional': typeof CadastroProfissionalRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/profissional/$slug': typeof ProfissionalSlugRoute
  '/_authenticated/painel/midia': typeof AuthenticatedPainelMidiaRoute
  '/_authenticated/painel/notificacoes': typeof AuthenticatedPainelNotificacoesRoute
  '/_authenticated/painel/pedidos': typeof AuthenticatedPainelPedidosRoute
  '/_authenticated/painel/perfil': typeof AuthenticatedPainelPerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/categorias'
    | '/entrar'
    | '/pedir-orcamento'
    | '/profissionais'
    | '/recuperar-senha'
    | '/reset-password'
    | '/favoritos'
    | '/painel'
    | '/cadastro/profissional'
    | '/categoria/$slug'
    | '/profissional/$slug'
    | '/painel/midia'
    | '/painel/notificacoes'
    | '/painel/pedidos'
    | '/painel/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/categorias'
    | '/entrar'
    | '/pedir-orcamento'
    | '/profissionais'
    | '/recuperar-senha'
    | '/reset-password'
    | '/favoritos'
    | '/painel'
    | '/cadastro/profissional'
    | '/categoria/$slug'
    | '/profissional/$slug'
    | '/painel/midia'
    | '/painel/notificacoes'
    | '/painel/pedidos'
    | '/painel/perfil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/buscar'
    | '/categorias'
    | '/entrar'
    | '/pedir-orcamento'
    | '/profissionais'
    | '/recuperar-senha'
    | '/reset-password'
    | '/_authenticated/favoritos'
    | '/_authenticated/painel'
    | '/cadastro/profissional'
    | '/categoria/$slug'
    | '/profissional/$slug'
    | '/_authenticated/painel/midia'
    | '/_authenticated/painel/notificacoes'
    | '/_authenticated/painel/pedidos'
    | '/_authenticated/painel/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CategoriasRoute: typeof CategoriasRoute
  EntrarRoute: typeof EntrarRoute
  PedirOrcamentoRoute: typeof PedirOrcamentoRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CadastroProfissionalRoute: typeof CadastroProfissionalRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProfissionalSlugRoute: typeof ProfissionalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir-orcamento': {
      id: '/pedir-orcamento'
      path: '/pedir-orcamento'
      fullPath: '/pedir-orcamento'
      preLoaderRoute: typeof PedirOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional/$slug': {
      id: '/profissional/$slug'
      path: '/profissional/$slug'
      fullPath: '/profissional/$slug'
      preLoaderRoute: typeof ProfissionalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/profissional': {
      id: '/cadastro/profissional'
      path: '/cadastro/profissional'
      fullPath: '/cadastro/profissional'
      preLoaderRoute: typeof CadastroProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/perfil': {
      id: '/_authenticated/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof AuthenticatedPainelPerfilRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/pedidos': {
      id: '/_authenticated/painel/pedidos'
      path: '/pedidos'
      fullPath: '/painel/pedidos'
      preLoaderRoute: typeof AuthenticatedPainelPedidosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/notificacoes': {
      id: '/_authenticated/painel/notificacoes'
      path: '/notificacoes'
      fullPath: '/painel/notificacoes'
      preLoaderRoute: typeof AuthenticatedPainelNotificacoesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/midia': {
      id: '/_authenticated/painel/midia'
      path: '/midia'
      fullPath: '/painel/midia'
      preLoaderRoute: typeof AuthenticatedPainelMidiaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelMidiaRoute: typeof AuthenticatedPainelMidiaRoute
  AuthenticatedPainelNotificacoesRoute: typeof AuthenticatedPainelNotificacoesRoute
  AuthenticatedPainelPedidosRoute: typeof AuthenticatedPainelPedidosRoute
  AuthenticatedPainelPerfilRoute: typeof AuthenticatedPainelPerfilRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelMidiaRoute: AuthenticatedPainelMidiaRoute,
  AuthenticatedPainelNotificacoesRoute: AuthenticatedPainelNotificacoesRoute,
  AuthenticatedPainelPedidosRoute: AuthenticatedPainelPedidosRoute,
  AuthenticatedPainelPerfilRoute: AuthenticatedPainelPerfilRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CategoriasRoute: CategoriasRoute,
  EntrarRoute: EntrarRoute,
  PedirOrcamentoRoute: PedirOrcamentoRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CadastroProfissionalRoute: CadastroProfissionalRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProfissionalSlugRoute: ProfissionalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
