// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygsitqilwlwqefwcpmtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnc2l0cWlsd2x3cWVmd2NwbXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM3MTYwNDEsImV4cCI6MjA5OTI5MjA0MX0.G8iM9e_CCAeWBUHTFY7ldq-twIOS6kXGHxzlazTlWpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});